version: '3'
services:
  selenium-chrome:
    container_name: selenium-chrome-study-163
    image: selenium/standalone-chrome-debug:3.141.59-neon
    environment:
      - VNC_NO_PASSWORD=1
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - 4444:4444
      - 15900:5900